#define cGREEN 33AA33
#define cYELLOW FFFF00
#define CGRAY 0xAFAFAFAA
#define CGREEN 0x33AA33AA
#define CRED 0xFF0000AA
#define CLIGHTRED 0xFF0033FF
#define CYELLOW 0xFFFF00AA
#define CWHITE 0xFFFFFFFF
#define CBLUE 0x4682B4AA
#define CLIGHTBLUE 0x33CCFFAA
#define CORANGE 0xFF9900AA
#define CSYSTEM 0xEFEFF7AA
#define CPINK 0xDD90FFFF
#define CBRIGHTRED 0xB2222200
#define CDARKGREEN 0x004400AA
#define CLIGHTGREEN 0x00FF00AA
#define CCON_GREEN 0x00FF00FF
#define CBROWN 0x8b4513FF
#define CINFO 0x269BD8FF
#define CBADINFO 0xFF182DFF
#define CADMIN 0xF36223FF
#define CDEPARTMENT 0x007FFFFF
#define CRADIO 0x6B8E23FF
#define cGRAY AFAFAF
#define cGREEN 33AA33
#define cRED FF0000
#define cLIGHTRED FF0033
#define cYELLOW FFFF00
#define cWHITE FFFFFF
#define cBLUE 4682B4
#define cLIGHTBLUE 33CCFF
#define cORANGE FF9900
#define cSYSTEM EFEFF7
#define cPINK E75480
#define cBRIGHTRED B22222
#define cDARKGREEN 004400
#define cLIGHTGREEN 00FF00
#define cCON_GREEN 00FF00
#define cBROWN 8b4513
#define cINFO 269BD8
#define cBADINFO FF182D
#define cDEPARTMENT 007FFF
#define cRADIO 6B8E23
#define COLOR_STANDART							0xADC7E7AA										//Цвет
#define COLOR_ISPOLZUY							0x7FB151FF										//Цвет
#define COLOR_GRAD1								0xB4B5B7FF										//Цвет
#define COLOR_BLUE								0x33AAFFFF										//Цвет
#define COLOR_GRAD2								0xBFC0C2FF										//Цвет
#define COLOR_INDIGO							0x4B00B0AA										//Цвет
#define COLOR_GRAD3								0xCBCCCEFF										//Цвет
#define COLOR_GRAD4								0xD8D8D8FF										//Цвет
#define COLOR_GRAD6								0xF0F0F0FF										//Цвет
#define COLOR_BLACK								0x000000AA										//Цвет
#define COLOR_GREY								0xAFAFAFAA										//Цвет
#define COLOR_GREEN								0x33AA33AA										//Цвет
#define COLOR_ORANGE							0xFF9900AA										//Цвет
#define COLOR_RED								0xAA3333AA										//Цвет
#define COLOR_LIGHTRED							0xFF6347AA										//Цвет
#define COLOR_LIGHTBLUE							0x33CCFFAA										//Цвет
#define COLOR_LIGHTGREEN						0x9ACD32AA										//Цвет
#define COLOR_YELLOW							0xFFFF00AA										//Цвет
#define COLOR_YELLOW2							0xF5DEB3AA										//Цвет
#define COLOR_WHITE								0xFFFFFFAA										//Цвет
#define COLOR_REDD								0xFF0000AA										//Цвет
#define COLOR_BROW								0xA85400AA										//Цвет
#define COLOR_FADE1								0xE6E6E6E6										//Цвет
#define COLOR_FADE2								0xC8C8C8C8										//Цвет
#define COLOR_FADE3								0xAAAAAAAA										//Цвет
#define COLOR_FADE4								0x8C8C8C8C										//Цвет
#define COLOR_FADE5								0x6E6E6E6E										//Цвет
#define COLOR_PURPLE							0xC2A2DAAA										//Цвет
#define COLOR_DBLUE								0x2641FEAA										//Цвет
#define COLOR_ALLDEPT							0xFF8282AA										//Цвет
#define COLOR_NEWS								0xFFA500AA										//Цвет
#define COLOR_LIFE								0xFEBC41AA										//Цвет
#define COLOR_OOC								0xE0FFFFAA										//Цвет
#define COLOR_BOX								0x00000050										//Цвет
#define COLOR_BBLUE								0x20A9FFAA										//Цвет
#define TEAM_BLUE_COLOR							0x8D8DFF00										//Цвет
#define TEAM_GROVE_COLOR						0x00D900C8										//Цвет
#define TEAM_VAGOS_COLOR						0xFFC801C8										//Цвет
#define TEAM_BALLAS_COLOR						0xD900D3C8										//Цвет
#define TEAM_AZTECAS_COLOR						0x01FCFFC8										//Цвет
#define TEAM_CYAN_COLOR							0xFF8282AA										//Цвет
#define TEAM_ORANGE_COLOR						0xFF830000										//Цвет
#define COLOR_ORANGE							0xFF9900AA										//Цвет
#define COLOR_RED								0xAA3333AA										//Цвет
#define COLOR_BORDER							0x00000AA
#define D_BASE 2285
#define D_RACE 2284
#define dVibMar 2112
#define dVibMarEdit 2113
#define dVibMarEditC1 2114
#define dVibMarEditC2 2115
#define dVibMarEditC3 2116
#define dVibGolos 2117
#define dMakeGun2 8585
#define dMakeGun 8586
#define dExamType 9900
#define dAutoExam1 9901
#define dAutoExam2 9902
#define dAutoExam3 9903
#define dAutoTest1 9904
#define dAutoTest2 9905
#define dAutoTest3 9906
#define dAutoTest4 9907
#define dAutoTest5 9908
#define dAirExam1 9910
#define dAirExam2 9911
#define dAirExam3 9912
#define dAirExam4 9913
#define dAirExam5 9914
#define dAirExam6 9915
#define dAirExam7 9916
#define dAirExam8 9917
#define dAirExam9 9918
#define dAirExam10 9919
#define dAirExam11 9920
#define dExamResult 9921
#define dAdvertSend 8100
#define dAdvertList 8101
#define dAdvertAction 8102
#define dAdvertEdit 8103
#define dSellCar 4938
#define dBusiness 9924
#define dBusinessBank 9925
#define dBusinessPut 9927
#define dBusinessGet 9928
#define CGREEN 			0x33AA33AA
#define COLOR_PAYCHEC   0xa4cd00AA
#define SCM 			SendClientMessage
stock Float:PointToPoint3D(Float:x1,Float:y1,Float:z1,Float:x2,Float:y2,Float:z2) return floatsqroot(floatadd(floatadd(floatpower(x2-x1,2),floatpower(y2-y1,2)),floatpower(z2-z1,2)));